Replace MSVC specific `strcpy_s` with `std::memcpy`
Fix build error on non-Windows systems:
> ```
> OP2-Landlord/Gui.cpp: In member function ‘Gui::AppState Gui::initialSetup()’:
> OP2-Landlord/Gui.cpp:88:27: error: ‘strcpy_s’ was not declared in this scope; did you mean ‘strcpy’?
>    88 |             std::ignore = strcpy_s(op2Path, mFileIo.folderPath().c_str());
>       |                           ^~~~~~~~
>       |                           strcpy
> ```

Make use of `std::string` internal buffer being null terminated, and ensure we copy the null terminator which is not included in `size()`. Never copy more than the lower of the buffer size or the source string length.