Add missing include for `<memory>` to `Graphics.cpp`
This is needed for `std::unique_ptr`, which is used by the `using` alias for `SdlSurface`.

Primary error:
> ```
> OP2-Landlord/Graphics.cpp:22:29: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
>    22 |     using SdlSurface = std::unique_ptr <SDL_Surface, SurfaceDeleter> ;
>       |                             ^~~~~~~~~~
> OP2-Landlord/Graphics.cpp:9:1: note: ‘std::unique_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
>     8 | #include <sstream>
>   +++ |+#include <memory>
> ```

Secondary error:
> ```
> OP2-Landlord/Graphics.cpp:24:5: error: ‘SdlSurface’ does not name a type; did you mean ‘SDL_Surface’?
>    24 |     SdlSurface createSurfaceFromBuffer(const void* buffer, const size_t buffersize)
>       |     ^~~~~~~~~~
>       |     SDL_Surface
> ```