Downgrade Docker base image to `ghcr.io/outpostuniverse/op2utility:1.2`
The older image is based on Ubuntu 24.04, while the newer version is based on Ubuntu 26.04.

It seems the newer version of Ubuntu includes a newer package of `imgui` which has a compatibility breaking change. The error message is:
> error: too few arguments to function 'void ImGui_ImplSDLRenderer2_RenderDrawData(ImDrawData*, SDL_Renderer*)'