Update GitHub Actions used in workflow to latest versions
Fix error:
> Error: This request has been automatically failed because it uses a deprecated version of `actions/cache: v2`. Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down

There are a number of other structural problems with the GitHub Actions workflows that cause them to fail. This fixes the first of them, allowing the others to be addressed more easily.